# Generated by Django 3.2.3 on 2021-10-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='Şirket İsmi')),
                ('company_type', models.CharField(max_length=15, verbose_name='Şirket Türü')),
                ('tax_administration', models.CharField(max_length=15, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(max_length=15, verbose_name='Vergi Numarası')),
                ('register_time', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=30, verbose_name='Adı')),
                ('contact_phone_number', models.CharField(max_length=15, verbose_name='İletişim Numarası')),
                ('contact_mail_addres', models.EmailField(max_length=254, verbose_name='İletişim Mail Adresi')),
                ('product_category', models.CharField(max_length=30, verbose_name='Ürün Kategorisi')),
                ('additional_information', models.CharField(max_length=50, verbose_name='Ek Bilgi')),
            ],
        ),
    ]
