# Generated by Django 3.2.8 on 2021-10-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedarikci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='register_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Kayıt Zamanı'),
        ),
    ]
